### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by drique** [camelaissani/loca#29]
Manhattan main image is not loading on newer versions of the code

This seems to be the related error:
```
(node:1951) UnhandledPromiseRejectionWarning: Error: Error in file: /usr/app/frontend/images/manhattan.jpg

Command failed: /usr/app/node_modules/mozjpeg/vendor/cjpeg
/usr/app/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
```

Probably because of this error when building docker image:
```
> mozjpeg@5.0.0 postinstall /usr/app/node_modules/mozjpeg
> node lib/install.js

  The `/usr/app/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  mozjpeg pre-build test failed
  compiling from source
  Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/usr/app/node_modules/mozjpeg/vendor" --bindir="/usr/app/node_modules/mozjpeg/vendor" --libdir="/usr/app/node_modules/mozjpeg/vendor" && make -j1 && make install -j1
Command failed: ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/usr/app/node_modules/mozjpeg/vendor" --bindir="/usr/app/node_modules/mozjpeg/vendor" --libdir="/usr/app/node_modules/mozjpeg/vendor"
configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by camelaissani** [comment]
Let me know if my fix works on your side.

**Comment by drique** [comment]
FIxed. 
Closing issue.
